# Generated by Django 5.1.1 on 2026-05-07 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_brain_auto_repair_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRepairMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_question', models.CharField(max_length=500)),
                ('question_examples', models.JSONField(blank=True, default=list)),
                ('recommended_chunk_ids', models.JSONField(blank=True, default=list)),
                ('related_entity_ids', models.JSONField(blank=True, default=list)),
                ('knowledge_gaps', models.JSONField(blank=True, default=list)),
                ('last_answer_confidence', models.FloatField(default=0)),
                ('status', models.CharField(default='improved', max_length=50)),
                ('times_applied', models.PositiveIntegerField(default=0)),
                ('last_repaired_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_repair_memories', to='core.brain')),
            ],
            options={
                'ordering': ['-last_repaired_at'],
                'constraints': [models.UniqueConstraint(fields=('brain', 'normalized_question'), name='retrieval_qrm_brain_question_unique')],
            },
        ),
    ]
