# Generated by Django 5.1.1 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retrieval", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryrepairmemory",
            name="status",
            field=models.CharField(default="resolved", max_length=50),
        ),
    ]
