# Generated by Django 5.1.1 on 2026-05-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entity',
            new_name='knowledge_e_name_9f3638_idx',
            old_name='knowledge_e_name_b74efc_idx',
        ),
        migrations.RenameIndex(
            model_name='relationship',
            new_name='knowledge_r_relatio_68eee9_idx',
            old_name='knowledge_r_relatio_2db149_idx',
        ),
    ]
