# Generated by Django 5.1.1 on 2026-05-05 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('knowledge', '0002_rename_knowledge_e_name_b74efc_idx_knowledge_e_name_9f3638_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='brain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='core.brain'),
        ),
        migrations.AddField(
            model_name='entity',
            name='brain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.brain'),
        ),
    ]
