# Generated by Django 5.1.1 on 2026-05-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_chatsession_brain_entity_brain'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='contradiction_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='contradiction_review_state',
            field=models.CharField(default='clear', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='subject_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='mention_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='retrieval_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='source_document_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='top_evidence_chunk_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='relationship',
            name='normalized_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
