# Generated by Django 5.1.1 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0004_claim_contradiction_flag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="contradiction_review_state",
            field=models.CharField(default="active", max_length=50),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
