# Generated by Django 6.0.5 on 2026-05-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_claim_review_states_and_session_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkentitymention',
            name='end_char',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chunkentitymention',
            name='start_char',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
