# Generated by Django 6.0.5 on 2026-05-11 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_document_structure_metadata_documentword"),
        ("knowledge", "0006_chunk_positional_metadata_and_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceSpan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quote_text", models.TextField()),
                ("span_start_char", models.IntegerField()),
                ("span_end_char", models.IntegerField()),
                (
                    "primary_locator_type",
                    models.CharField(
                        choices=[
                            ("pdf_page_bbox", "PDF page bounding boxes"),
                            ("text_char_range", "Text character range"),
                            ("docx_paragraph_range", "DOCX paragraph range"),
                            ("pptx_slide_text_range", "PPTX slide text range"),
                            ("sheet_cell_range", "Sheet cell range"),
                            ("html_dom_text_range", "HTML text range"),
                        ],
                        max_length=64,
                    ),
                ),
                ("locator_payload", models.JSONField(blank=True, default=dict)),
                (
                    "created_from",
                    models.CharField(
                        choices=[("chat", "Chat"), ("review", "Review"), ("manual", "Manual")],
                        default="chat",
                        max_length=32,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("needs_review", "Needs review"),
                        ],
                        default="unreviewed",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_spans",
                        to="knowledge.chatmessage",
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_spans",
                        to="documents.chunk",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_spans",
                        to="documents.document",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="evidencespan",
            index=models.Index(fields=["document", "chunk"], name="knowledge_e_documen_b4fce0_idx"),
        ),
        migrations.AddIndex(
            model_name="evidencespan",
            index=models.Index(fields=["chat_message", "created_at"], name="knowledge_e_chat_me_29e9cf_idx"),
        ),
        migrations.AddIndex(
            model_name="evidencespan",
            index=models.Index(fields=["primary_locator_type", "review_status"], name="knowledge_e_primary_6ccb16_idx"),
        ),
    ]
