# Generated by Django 5.1.1 on 2026-05-05 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0002_document_llm_model_document_llm_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='brain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.brain'),
        ),
    ]
