# Generated by Django 5.1.1 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_ingestionjob_metadata_chunkextractionartifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunkextractionartifact",
            name="empty_verification_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chunkextractionartifact",
            name="empty_verification_status",
            field=models.CharField(
                choices=[
                    ("not_needed", "Not needed"),
                    ("verified_empty", "Verified empty"),
                    ("retry_recommended", "Retry recommended"),
                ],
                default="not_needed",
                max_length=50,
            ),
        ),
    ]
