# Generated by Django 5.1.1 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_chunkextractionartifact_empty_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source_authority",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("user_provided", "User Provided"),
                    ("secondary", "Secondary Source"),
                    ("primary", "Primary Source"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="source_observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="source_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
