# Generated by Django 6.0.5 on 2026-05-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_source_authority_and_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='certainty_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='content_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
