# Generated by Django 6.0.5 on 2026-05-11 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_chunk_positional_metadata_and_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="structure_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="DocumentWord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("page_number", models.PositiveIntegerField()),
                ("text", models.CharField(max_length=255)),
                ("start_char", models.PositiveIntegerField()),
                ("end_char", models.PositiveIntegerField()),
                ("bbox", models.JSONField(blank=True, default=list)),
                ("block_index", models.IntegerField(default=0)),
                ("line_index", models.IntegerField(default=0)),
                ("reading_order", models.IntegerField(default=0)),
                (
                    "extraction_source",
                    models.CharField(
                        choices=[("native_pdf", "Native PDF"), ("ocr", "OCR")],
                        default="native_pdf",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_words",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document_id", "page_number", "reading_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="documentword",
            index=models.Index(fields=["document", "page_number", "reading_order"], name="documents_d_documen_1e971c_idx"),
        ),
        migrations.AddIndex(
            model_name="documentword",
            index=models.Index(fields=["document", "start_char", "end_char"], name="documents_d_documen_b8619b_idx"),
        ),
    ]
